services:
  ollama-gpu:
    networks:
      - application-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
          memory: 15G
          cpus: '6'
        limits:
          memory: 20G
          cpus: '8'
  ollama-cpu:
    networks:
      - application-network
    deploy:
      resources:
        reservations:
          memory: 5G
          cpus: '2'
        limits:
          memory: 5G
          cpus: '2'
  application:
    networks:
      - application-network
    deploy:
      resources:
        reservations:
          memory: 5G
          cpus: '1'
        limits:
          memory: 6G
          cpus: '1'
networks:
  application-network: