services:
  ollama-gpu:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
          memory: 10G
          cpus: '2'
        limits:
          memory: 10g
          cpus: '2'
  ollama-cpu:
    deploy:
      resources:
        reservations:
          memory: 5G
          cpus: '2'
        limits:
          memory: 5g
          cpus: '2'