services:
  ollama-gpu:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
          memory: 15G
          cpus: '6'
        limits:
          memory: 20g
          cpus: '8'
  ollama-cpu:
    deploy:
      resources:
        reservations:
          memory: 5G
          cpus: '2'
        limits:
          memory: 5g
          cpus: '2'