services:
  ollama-gpu:
    image: ollama/ollama
    volumes:
      - ./models-gpu:/models
      - ./ollama-gpu-data:/root/.ollama
    ports:
      - "11434:11434"
  ollama-cpu:
    image: ollama/ollama
    volumes:
      - ./models-cpu:/models
      - ./ollama-gpu-data:/root/.ollama
    ports:
      - "11435:11434"